[package]
name = "cef-dll-sys"
description = "cef-rs sys crate"
links = "cef_dll_wrapper"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
doctest = false

[features]
default = ["download"]
dox = []
sandbox = []
download = ["dep:serde_json", "download-cef/download"]

[package.metadata.docs.rs]
features = ["dox"]

[build-dependencies]
anyhow.workspace = true
cmake.workspace = true
download-cef = { workspace = true, default-features = false }
serde_json = { workspace = true, optional = true }
