[package]
name = "download-cef"
description = "Download and extract pre-built CEF (Chromium Embedded Framework) archives."
version = "2.3.2"

edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
regex.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

bzip2 = "0.6"
indicatif = "0.18"
sha1_smol = "1"
tar = "0.4"
ureq = { version = "3", features = ["json", "socks-proxy"] }
fs-err = "3.2.2"
